Repository prgrms-web-devcourse/Team-DarkNight-Kkini-BE, pull requests merged in 2023-03, with the labels that each got.

#49 [#24] Swagger 문서에 상세한 설명이 나올 수 있도록 테스트 수정
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/api/UserControllerTest.java
Labels: ✅ Test, 📝 Docs

#41 [#40] flyway DB 변경 스크립트 작성 및 엔티티에 변경된 내용 반영
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/model/CrewMember.java
  src/main/resources/db/migration/V2.3__alter_review_table.sql
  src/main/resources/db/migration/V2.4__modify_ERD.sql
  src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
  src/test/resources/schema.sql
Labels: ♻️ Refactor

#55 [#54] 검색 범위 거리를 프론트에서 파라미터로 받도록 수정
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/DistanceRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
Labels: ♻️ Refactor, ✅ Test

#57 [#56] 가게 테이블 컬럼 추가
  src/main/resources/db/migration/V2.5__alter_store_table.sql
Labels: ♻️ Refactor

#59 [#58] 가게 아이디로 가게 조회 기능 구현
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/store/api/StoreController.java
  src/main/java/com/prgrms/mukvengers/domain/store/dto/response/StoreResponse.java
  src/main/java/com/prgrms/mukvengers/domain/store/mapper/StoreMapper.java
  src/main/java/com/prgrms/mukvengers/domain/store/service/StoreService.java
  src/main/java/com/prgrms/mukvengers/domain/store/service/StoreServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/service/StoreServiceTest.java
Labels: 🚀 Feat, ✅ Test

#66 [#61] Flyway를 이용해 crewMember, review 테이블 수정
  src/main/resources/db/migration/V2.6__delete_crewMember_column.sql
  src/main/resources/db/migration/V2.7__alter_review_table.sql
  src/test/resources/schema.sql
Labels: ♻️ Refactor

#68 [#67] DB 변경으로 인한 CrewMember, Review Entity 수정 및 ObjectProvider 추가
  src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/model/CrewMember.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java
  src/main/java/com/prgrms/mukvengers/domain/review/dto/request/CreateLeaderReviewRequest.java
  src/main/java/com/prgrms/mukvengers/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/prgrms/mukvengers/domain/review/mapper/ReviewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/review/model/Review.java
  src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewMemberObjectProvider.java
  src/test/java/com/prgrms/mukvengers/utils/ReviewObjectProvider.java
  src/test/java/com/prgrms/mukvengers/utils/UserObjectProvider.java
  src/test/resources/schema.sql
Labels: ♻️ Refactor

#70 [#64] 데이터베이스 수정
  src/main/resources/db/migration/V2.8_modify_erd_sprint3.sql
  src/test/resources/schema.sql
Labels: ♻️ Refactor

#74 [#71] 테스트 스키마 변경하고 코드 수정
  src/main/java/com/prgrms/mukvengers/domain/store/dto/request/CreateStoreRequest.java
  src/main/java/com/prgrms/mukvengers/domain/store/dto/response/StoreResponse.java
  src/main/java/com/prgrms/mukvengers/domain/store/mapper/StoreMapper.java
  src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java
  src/main/resources/db/migration/V2.5__alter_store_table.sql
  src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/service/StoreServiceTest.java
  src/test/java/com/prgrms/mukvengers/utils/StoreObjectProvider.java
  src/test/resources/schema.sql
Labels: ♻️ Refactor, ✅ Test

#76 [#62] 모임 단건 조회
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/Category.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/Status.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
Labels: 🚀 Feat, ✅ Test

#73 [#38] Refresh Token 기능 구현
  src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/dto/AuthUserInfo.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/service/OAuthService.java
  src/main/java/com/prgrms/mukvengers/global/security/token/api/TokenController.java
  src/main/java/com/prgrms/mukvengers/global/security/token/dto/request/CreateAccessTokenRequest.java
  src/main/java/com/prgrms/mukvengers/global/security/token/dto/response/TokenResponse.java
  src/main/java/com/prgrms/mukvengers/global/security/token/exception/RefreshTokenNotFoundException.java
  src/main/java/com/prgrms/mukvengers/global/security/token/model/Token.java
  src/main/java/com/prgrms/mukvengers/global/security/token/repository/TokenRepository.java
  src/main/java/com/prgrms/mukvengers/global/security/token/service/TokenService.java
Labels: 🚀 Feat

#78 [#38] RefreshToken 기능에 Redis 적용
  build.gradle
  docker-compose.yml
  src/main/java/com/prgrms/mukvengers/global/config/redis/RedisConfig.java
  src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/prgrms/mukvengers/global/security/token/model/RefreshToken.java
  src/main/java/com/prgrms/mukvengers/global/security/token/repository/RefreshTokenRepository.java
  src/main/resources/application-db.yml
  src/main/resources/application-security.yml
  src/main/resources/application-test.yml
  src/test/java/com/prgrms/mukvengers/config/JwtConfig.java
  src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProviderTest.java
Labels: 🛠 Setting

#83 [#38] RefreshToken 기능 통합 구현 및 JWT 기능과 분리 작업
  src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/prgrms/mukvengers/global/security/token/api/TokenController.java
  src/main/java/com/prgrms/mukvengers/global/security/token/dto/request/RefreshTokenRequest.java
  src/main/java/com/prgrms/mukvengers/global/security/token/repository/TokenRepository.java
  src/main/java/com/prgrms/mukvengers/global/security/token/service/TokenService.java
  src/test/java/com/prgrms/mukvengers/config/JwtConfig.java
  src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProviderTest.java
Labels: ♻️ Refactor, 🐛 Bug

#81 [#65] 사용자의 밥 모임 조회
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/MyCrewResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java
  src/test/java/com/prgrms/mukvengers/base/ServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
Labels: 🚀 Feat, ♻️ Refactor

#85 [#77] 사용자 프로필 이미지를 S3에 저장한다.
  build.gradle
  src/main/java/com/prgrms/mukvengers/global/aws/api/AwsS3Controller.java
  src/main/java/com/prgrms/mukvengers/global/aws/dto/AwsS3.java
  src/main/java/com/prgrms/mukvengers/global/aws/service/AwsS3Service.java
  src/main/java/com/prgrms/mukvengers/global/config/s3/AwsConfig.java
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🚀 Feat

#87 [#8] 구글 Redirect_URI를 인식하지 못하는 문제 해결
  Dockerfile
  docker-compose.yml
  src/main/resources/application-security.yml
Labels: 🐛 Bug

#92 CORS 설정에 OPTIONS 메서드 추가
  src/main/java/com/prgrms/mukvengers/global/config/web/WebConfig.java
Labels: 🐛 Bug

#93 fix(CORS): CORS 설정에서 allowedHeaders 추가
  src/main/java/com/prgrms/mukvengers/global/config/web/WebConfig.java
Labels: 🐛 Bug

#84 [#44] 밥 모임 생성 시 생성 유저 를 방 모임원으로 만들고 방장 권한 부여
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/CreateCrewRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/mapper/CrewMemberMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberService.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
Labels: ♻️ Refactor, ✅ Test

#88 [#86] 가게 테이블 수정
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/store/api/StoreController.java
  src/main/java/com/prgrms/mukvengers/domain/store/dto/request/CreateStoreRequest.java
  src/main/java/com/prgrms/mukvengers/domain/store/dto/response/StoreResponse.java
  src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java
  src/main/java/com/prgrms/mukvengers/domain/store/repository/StoreRepository.java
  src/main/java/com/prgrms/mukvengers/domain/store/service/StoreService.java
  src/main/java/com/prgrms/mukvengers/domain/store/service/StoreServiceImpl.java
  src/main/resources/db/migration/V2.9__alter_store_table.sql
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/repository/StoreRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/service/StoreServiceTest.java
  src/test/java/com/prgrms/mukvengers/utils/StoreObjectProvider.java
  src/test/resources/schema.sql
Labels: ♻️ Refactor

#95 [#94] Store conflict 수정
  src/test/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeServiceTest.java
Labels: 🐛 Bug

#99 [#89] 내가 작성한 리뷰 & 나에 대한 리뷰 API 생성
  src/main/java/com/prgrms/mukvengers/domain/crewmember/exception/LeaderNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/exception/MemberNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/review/api/ReviewController.java
  src/main/java/com/prgrms/mukvengers/domain/review/exception/ReviewNotAccessException.java
  src/main/java/com/prgrms/mukvengers/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/review/mapper/ReviewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/review/model/Review.java
  src/main/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepository.java
  src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewService.java
  src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/user/model/User.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProviderTest.java
  src/test/java/com/prgrms/mukvengers/utils/ReviewObjectProvider.java
  src/test/resources/schema.sql
Labels: ♻️ Refactor

#96 [#91] 신청서(proposal) 테이블 추가 및 리뷰(review) 컬럼명 수정
  src/main/resources/db/migration/V2.8__modify_erd_sprint3.sql
Labels: ♻️ Refactor

#101 [#100] 신청서 도메인 생성
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/CreateCrewRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/CrewStatus.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/model/Proposal.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/model/vo/ProposalStatus.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
Labels: 🚀 Feat

#104 [#97] 사용자가 방장인 모임에 참여 신청이 온 신청서 조회
  src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/dto/response/ProposalResponse.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/dto/response/ProposalResponses.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/mapper/ProposalMapper.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/base/ServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/ProposalObjectProvider.java
Labels: 🚀 Feat, ✅ Test

#106 [#105] 모임 생성시 가게 정보가 없을 경우 가게를 저장한다.
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/CreateCrewRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
Labels: ♻️ Refactor, ✅ Test

#110 [#24] 운영 서버 배포전 v1.0.0 - SNAPSHOT 버전 설정하기
  Dockerfile
  build.gradle
Labels: ♻️ Refactor, 🌏 Release

#111 [#24] cp: target 'deploy/application.jar' is not a directory 문제 해결
  build.gradle
Labels: 🐛 Bug

#114 [#113] 가게 이미지 Url DB 저장 데이터 타입 수정
  src/main/resources/db/migration/V3.0__alter_store_table.sql
  src/test/resources/schema.sql
Labels: ♻️ Refactor

#115 [#98] 사용자가 참여를 위해 작성한 신청서 조회
  src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
Labels: 🚀 Feat, ✅ Test

#121 [#120] 모임 생성시 ResponseBody에 모임 아이디를 반환
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
Labels: ♻️ Refactor, ✅ Test

#117 [#116] Review 필드명 수정 및 Review Controller 테스트 컨벤션 리팩토링
  src/main/java/com/prgrms/mukvengers/domain/review/dto/request/CreateLeaderReviewRequest.java
  src/main/java/com/prgrms/mukvengers/domain/review/dto/request/CreateMemberReviewRequest.java
  src/main/java/com/prgrms/mukvengers/domain/review/dto/response/ReviewResponse.java
  src/main/java/com/prgrms/mukvengers/domain/review/mapper/ReviewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/review/model/Review.java
  src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/ReviewObjectProvider.java
  src/test/resources/schema.sql
Labels: ♻️ Refactor, ✅ Test

#112 [#107] 모임 조회시 해당 모임의 모임원의 정보도 같이 반환한다.
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewDetailResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewPageResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewResponses.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/MyCrewResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/dto/response/CrewMemberResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/mapper/CrewMemberMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/model/CrewMember.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/model/vo/CrewMemberRole.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberService.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImpl.java
  src/main/resources/db/migration/V3.1__alter_crew_member_table.sql
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewMemberObjectProvider.java
  src/test/resources/schema.sql
Labels: ♻️ Refactor, ✅ Test

#122 [#8] Cookie에 SameSite 설정을 None으로 변경
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
Labels: 🐛 Bug

#124 [#123] 사용자 거리기반 모임 조회 응답 값 수정
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewLocationResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewLocationResponses.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
Labels: ♻️ Refactor, ✅ Test

#130 [#127] 모임 단건 조회 응답 DTO 수정
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewDetailResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
Labels: ♻️ Refactor, ✅ Test

#128 [#126] 신청서(proposal) 작성 API 생성
  src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/dto/request/CreateProposalRequest.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/mapper/ProposalMapper.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewMemberObjectProvider.java
  src/test/java/com/prgrms/mukvengers/utils/ProposalObjectProvider.java
Labels: 🚀 Feat, ✅ Test

#134 모집 상태 변경(모집 중-> 모집 종료) 기능
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/UpdateStatusRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crew/exception/CrewStatusException.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/CrewStatus.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/exception/NotLeaderException.java
  src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
Labels: 🚀 Feat, ✅ Test

#138 [#38] Cookie httpOnly 속성 변경
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/prgrms/mukvengers/global/security/token/api/TokenController.java
  src/main/java/com/prgrms/mukvengers/global/utils/CookieUtil.java
Labels: ♻️ Refactor, 🐛 Bug

#137 [#136] 신청서 단건 조회 기능
  src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/exception/ProposalNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
Labels: 🚀 Feat, ✅ Test

#142 [#139] 리뷰 페이지 조회 기능 구현
  src/main/java/com/prgrms/mukvengers/domain/review/api/ReviewController.java
  src/main/java/com/prgrms/mukvengers/domain/review/dto/response/RevieweeListResponse.java
  src/main/java/com/prgrms/mukvengers/domain/review/mapper/ReviewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepository.java
  src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewService.java
  src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepositoryTest.java
Labels: 🚀 Feat, ✅ Test

#141 [#135] 모집 상태 변경(모집 종료-> 식사 완료) 기능
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/UpdateStatusRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
Labels: 🚀 Feat, ✅ Test

#131 [#118] EventListener를 사용하여 다른 도메인의 서비스 호출하기
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/event/CreateCrewEvent.java
  src/main/java/com/prgrms/mukvengers/domain/crew/handler/CrewEventHandler.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
Labels: ♻️ Refactor

#75 [#72] logback 설정 변경 및 cloudwatch로 관리
  .github/workflows/deploy-to-prod.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/prgrms/mukvengers/global/common/annotation/SlackNotification.java
  src/main/java/com/prgrms/mukvengers/global/common/dto/RequestInfo.java
  src/main/java/com/prgrms/mukvengers/global/config/slack/SlackNotificationAspect.java
  src/main/java/com/prgrms/mukvengers/global/config/thread/ThreadPoolConfig.java
  src/main/java/com/prgrms/mukvengers/global/exception/GlobalExceptionHandler.java
  src/main/resources/appender/kkini-console-appender.xml
  src/main/resources/appender/kkini-prod-error-appender.xml
  src/main/resources/appender/kkini-prod-info-appender.xml
  src/main/resources/appender/kkini-slack-appender.xml
  src/main/resources/application-slack.yml
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/logback.xml
  src/test/resources/application.yml
Labels: 🛠 Setting

#144 [#143] 신청서(Proposal) 수락/거절 상태값 변경 API 수정 및 기타 수정
  src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
Labels: ♻️ Refactor, ✅ Test

#149 [#148] Swagger UI에서 docExpansion 설정 'none'으로 변경
  build.gradle
Labels: ♻️ Refactor, 📝 Docs

#150 [#146] 모임 조회 응답 필드 변경
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewDetailResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewLocationResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/model/vo/ProposalStatus.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
Labels: ♻️ Refactor, ✅ Test

#153 test(Crew): 테스트 코드 중복 제거
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/api/UserControllerTest.java
Labels: ♻️ Refactor, ✅ Test

#155 Proposal api 테스트 코드 수정
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
Labels: ♻️ Refactor, ✅ Test

#157 [#69] 웹 소켓을 활용한 채팅방 기능 구현
  build.gradle
  src/main/java/com/prgrms/mukvengers/domain/chat/api/ChatController.java
  src/main/java/com/prgrms/mukvengers/domain/chat/dto/request/ChatRequest.java
  src/main/java/com/prgrms/mukvengers/domain/chat/dto/request/MessageType.java
  src/main/java/com/prgrms/mukvengers/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/prgrms/mukvengers/domain/chat/dto/response/ChatsInCrew.java
  src/main/java/com/prgrms/mukvengers/domain/chat/exception/WebSocketException.java
  src/main/java/com/prgrms/mukvengers/domain/chat/handler/StompHandler.java
  src/main/java/com/prgrms/mukvengers/domain/chat/handler/WebSocketEventListener.java
  src/main/java/com/prgrms/mukvengers/domain/chat/mapper/ChatMapper.java
  src/main/java/com/prgrms/mukvengers/domain/chat/model/Chat.java
  src/main/java/com/prgrms/mukvengers/domain/chat/repository/ChatRepository.java
  src/main/java/com/prgrms/mukvengers/domain/chat/service/ChatService.java
  src/main/java/com/prgrms/mukvengers/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java
  src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java
  src/main/java/com/prgrms/mukvengers/global/config/websocket/WebSocketConfig.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/main/java/com/prgrms/mukvengers/global/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/mukvengers/global/utils/ExtractUtil.java
  src/main/resources/db/migration/V3.2__alter_chat_table.sql
  src/main/resources/templates/index.html
  src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java
  src/test/java/com/prgrms/mukvengers/base/ServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/chat/repository/ChatRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/chat/service/ChatServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/utils/ChatObjectProvider.java
  src/test/resources/schema.sql
Labels: 🚀 Feat

#161 [#156] Crew 생성기능 리펙터링
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/event/CreateCrewEvent.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/CreateCrewRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/handler/CrewEventHandler.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberService.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/store/dto/request/CreateStoreRequest.java
  src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java
  src/main/resources/db/migration/V3.2__alter_store_table.sql
  src/test/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java
  src/test/resources/schema.sql
Labels: ♻️ Refactor, ✅ Test

#163 [#162] 신청서 재작성시 Duplicate Custom exception 발생
  src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/exception/CrewMemberOverCapacity.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/exception/DuplicateProposalException.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/exception/ExistCrewMemberRoleException.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
Labels: ♻️ Refactor, ✅ Test

#160 [#148] 프로젝트 종료 전 코드 스타일 정리
  .github/workflows/deploy-to-dev.yml
  .github/workflows/deploy-to-prod.yml
  src/main/java/com/prgrms/mukvengers/domain/chat/api/ChatController.java
  src/main/java/com/prgrms/mukvengers/domain/chat/handler/WebSocketEventListener.java
  src/main/java/com/prgrms/mukvengers/domain/chat/repository/ChatRepository.java
  src/main/java/com/prgrms/mukvengers/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/comment/model/Comment.java
  src/main/java/com/prgrms/mukvengers/global/aws/api/AwsS3Controller.java
  src/main/java/com/prgrms/mukvengers/global/aws/service/AwsS3Service.java
  src/main/java/com/prgrms/mukvengers/global/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/prgrms/mukvengers/global/slack/SlackNotificationAspect.java
  src/main/java/com/prgrms/mukvengers/global/slack/annotation/SlackNotification.java
  src/main/java/com/prgrms/mukvengers/global/slack/dto/RequestInfo.java
  src/main/java/com/prgrms/mukvengers/global/utils/CookieUtil.java
  src/main/java/com/prgrms/mukvengers/global/utils/PointConverter.java
  src/main/resources/application-slack.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V3.4__drop_comment_table.sql
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: 🌏 Release

#164 [#148] Release v1.0.1
  Dockerfile
  build.gradle
  src/main/java/com/prgrms/mukvengers/domain/proposal/dto/response/ProposalResponse.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/mapper/ProposalMapper.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
  src/main/java/com/prgrms/mukvengers/global/exception/GlobalExceptionHandler.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
Labels: 🌏 Release

#166 [#165] 밥모임의 채팅내역을 조회하는 api 추가
  src/main/java/com/prgrms/mukvengers/domain/chat/api/ChatController.java
  src/main/java/com/prgrms/mukvengers/domain/chat/dto/response/ChatResponse.java
  src/main/java/com/prgrms/mukvengers/domain/chat/dto/response/ChatResponses.java
  src/main/java/com/prgrms/mukvengers/domain/chat/repository/ChatRepository.java
  src/main/java/com/prgrms/mukvengers/domain/chat/service/ChatService.java
  src/main/java/com/prgrms/mukvengers/domain/chat/service/ChatServiceImpl.java
  src/test/java/com/prgrms/mukvengers/base/ServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/chat/service/ChatServiceImplTest.java
Labels: 🚀 Feat

#167 프로젝트 단위 기간 종료 후 리드 미에 작업 사항 설명 추가
  README.md
Labels: 📝 Docs

#170 [#169] 모임 상태 자동 변경 프로세스 구현
  src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java
  src/main/java/com/prgrms/mukvengers/global/scheduler/Scheduler.java
  src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java
Labels: 🚀 Feat, ✅ Test

#171 [#168] 모임 퇴장 기능
  src/main/java/com/prgrms/mukvengers/domain/crew/exception/CrewNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/api/CrewMemberController.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/dto/response/CrewMemberResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/exception/CrewMemberNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/mapper/CrewMemberMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberService.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImpl.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/api/CrewMemberControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java
Labels: 🚀 Feat, ✅ Test

#173 [#172] 모임원 강퇴 기능
  src/main/java/com/prgrms/mukvengers/domain/crewmember/api/CrewMemberController.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/dto/request/UpdateCrewMemberRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/exception/NotMemberException.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/model/CrewMember.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberService.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImpl.java
  src/test/java/com/prgrms/mukvengers/base/ServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java
Labels: 🚀 Feat, ✅ Test

#175 [#174] 무중단 배포 적용
  .github/workflows/deploy-to-dev.yml
  deploy.sh
  docker-compose.yml
Labels: 💣 CI/CD

#181 [#180] Github Action Error
  settings.gradle
Labels: 🐛 Bug, 🛠 Setting

#182 [#176] 신청서 삭제
  src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/user/exception/InvalidUserException.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/main/java/com/prgrms/mukvengers/global/scheduler/Scheduler.java
  src/main/resources/application.yml
  src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepositoryTest.java
Labels: 🚀 Feat, ✅ Test

#184 Chat-GPT를 이용한 코드리뷰 기능 추가
  .github/workflows/code-review-by-chat-gpt.yml
Labels: 🚀 Feat, 💣 CI/CD, 🛠 Setting
