Repository prgrms-web-devcourse/Team-DarkNight-Kkini-BE, pull requests merged in 2023-04, with the labels that each got.

#185 [#177] Spring Security 인증 절차 기능 분리 작업
  .github/workflows/code-review-by-chat-gpt.yml
  build.gradle
  src/main/java/com/prgrms/mukvengers/domain/chat/handler/StompHandler.java
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/api/CrewMemberController.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
  src/main/java/com/prgrms/mukvengers/domain/review/api/ReviewController.java
  src/main/java/com/prgrms/mukvengers/domain/review/mapper/ReviewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/user/api/UserController.java
  src/main/java/com/prgrms/mukvengers/domain/user/mapper/UserMapper.java
  src/main/java/com/prgrms/mukvengers/domain/user/service/DefaultUserService.java
  src/main/java/com/prgrms/mukvengers/domain/user/service/UserService.java
  src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java
  src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/dto/AuthUserInfo.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/dto/CustomOAuth2User.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationFailureHandler.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/mapper/OAuthMapper.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/repository/HttpCookieOAuthAuthorizationRequestRepository.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/service/OAuthService.java
  src/main/java/com/prgrms/mukvengers/global/security/token/dto/Tokens.java
  src/main/java/com/prgrms/mukvengers/global/security/token/dto/jwt/JwtAuthentication.java
  src/main/java/com/prgrms/mukvengers/global/security/token/dto/jwt/JwtAuthenticationToken.java
  src/main/java/com/prgrms/mukvengers/global/security/token/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/prgrms/mukvengers/global/security/token/filter/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/mukvengers/global/security/token/service/JwtTokenProvider.java
  src/main/java/com/prgrms/mukvengers/global/security/token/service/TokenService.java
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/config/JwtConfig.java
  src/test/java/com/prgrms/mukvengers/domain/chat/repository/ChatRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/filter/JwtAuthenticationTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/filter/JwtTokenProviderTest.java
Labels: ♻️ Refactor

#187 [#186] redirectUri에 한글이 들어가면 에러 터지는 문제 해결
  src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationFailureHandler.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/repository/HttpCookieOAuthAuthorizationRequestRepository.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
Labels: 🐛 Bug

#192 [#189] 강퇴, 퇴장 로직 수정
  src/main/generated/com/prgrms/mukvengers/domain/crewmember/mapper/CrewMemberMapperImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImpl.java
Labels: 🐛 Bug

#191 [#190] Sentry 설정 추가
  build.gradle
  src/main/resources/application.yml
Labels: 🛠 Setting

#188 [#179] User 매너 온도 BigDecimal 타입으로 변경하여 소수점 에러 해결
  src/main/java/com/prgrms/mukvengers/domain/user/dto/response/UserProfileResponse.java
  src/main/java/com/prgrms/mukvengers/domain/user/model/User.java
  src/main/resources/db/migration/V4__alter_user_table.sql
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/api/UserControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/model/UserTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/service/UserServiceTest.java
  src/test/resources/schema.sql
Labels: ♻️ Refactor, ✅ Test

#196 [#195] 밤 모임 리스트 조회 범위 수정
  src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java
Labels: ♻️ Refactor

#198 [#197] 강퇴, 퇴장 로직 수정하여 배포합니다.
  src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java
Labels: 🐛 Bug, 🌏 Release

#200 [#199] 모임 생성 코드 리펙터링
  src/main/generated/com/prgrms/mukvengers/domain/crewmember/mapper/CrewMemberMapperImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/event/CreateCrewEvent.java
  src/main/java/com/prgrms/mukvengers/domain/crew/handler/CrewEventHandler.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
Labels: ♻️ Refactor

#202 refactor(crew): 내 모임 조회 코드 리펙터링
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewResponses.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/MyCrewResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/dto/response/MyCrewMemberResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/mapper/CrewMemberMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java
  src/main/java/com/prgrms/mukvengers/domain/user/repository/UserRepository.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
Labels: ♻️ Refactor
