Repository prgrms-web-devcourse/Team-DarkNight-Kkini-BE, pull requests merged in 2023-02, with the labels that each got.

#2 [#1] 프로젝트 초기 설정 작업
  .github/ISSUE_TEMPLATE/bakclog-template.md
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/discussion-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/prgrms/mukvengers/MukvengersApplication.java
  src/main/java/com/prgrms/mukvengers/global/common/domain/BaseEntity.java
  src/main/java/com/prgrms/mukvengers/global/common/dto/ApiResponse.java
  src/main/java/com/prgrms/mukvengers/global/common/dto/ErrorResponse.java
  src/main/java/com/prgrms/mukvengers/global/common/dto/IdResponse.java
  src/main/java/com/prgrms/mukvengers/global/config/message/MessageConfig.java
  src/main/java/com/prgrms/mukvengers/global/config/p6spy/P6spyConfig.java
  src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java
  src/main/java/com/prgrms/mukvengers/global/config/web/WebConfig.java
  src/main/java/com/prgrms/mukvengers/global/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/mukvengers/global/exception/ServiceException.java
  src/main/java/com/prgrms/mukvengers/global/log/CustomRequestLoggingFilter.java
  src/main/java/com/prgrms/mukvengers/global/utils/MessageUtil.java
  src/main/java/com/prgrms/mukvengers/global/utils/ValidateUtil.java
  src/main/resources/application-db.yml
  src/main/resources/application-security.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1__init.sql
  src/main/resources/logback.xml
  src/main/resources/messages/exceptions/exception.properties
  src/test/java/com/prgrms/mukvengers/MukvengersApplicationTests.java
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java
  src/test/java/com/prgrms/mukvengers/base/ServiceTest.java
  src/test/java/com/prgrms/mukvengers/base/SliceTest.java
  src/test/java/com/prgrms/mukvengers/config/RestDocsConfig.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: 🛠 Setting

#7 [#4] CI - GitHub Actions를 활용해서 Gradle Build 적용
  .github/workflows/ci-gradle-build.yml
Labels: 💣 CI/CD

#9 [#5] ERD를 바탕으로 도메인 엔티티 구현
  .github/ISSUE_TEMPLATE/refactor-template.md
  build.gradle
  src/main/java/com/prgrms/mukvengers/domain/comment/model/Comment.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/Category.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/Status.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/model/CrewMember.java
  src/main/java/com/prgrms/mukvengers/domain/post/model/Post.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/model/Proposal.java
  src/main/java/com/prgrms/mukvengers/domain/review/model/Review.java
  src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java
  src/main/java/com/prgrms/mukvengers/domain/user/model/User.java
  src/main/resources/db/migration/V1__init.sql
  src/test/resources/schema.sql
Labels: 🚀 Feat

#17 [#3] 유저 RUD 기능 구현
  src/main/java/com/prgrms/mukvengers/domain/user/dto/request/UpdateUserRequest.java
  src/main/java/com/prgrms/mukvengers/domain/user/dto/response/UserProfileResponse.java
  src/main/java/com/prgrms/mukvengers/domain/user/exception/UserNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/user/mapper/UserMapper.java
  src/main/java/com/prgrms/mukvengers/domain/user/model/User.java
  src/main/java/com/prgrms/mukvengers/domain/user/repository/UserRepository.java
  src/main/java/com/prgrms/mukvengers/domain/user/service/DefaultUserService.java
  src/main/java/com/prgrms/mukvengers/domain/user/service/UserService.java
  src/main/java/com/prgrms/mukvengers/global/common/domain/BaseEntity.java
  src/main/java/com/prgrms/mukvengers/global/common/dto/ErrorResponse.java
  src/main/java/com/prgrms/mukvengers/global/common/dto/IdResponse.java
  src/main/java/com/prgrms/mukvengers/global/config/jpa/JpaConfig.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/main/java/com/prgrms/mukvengers/global/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/mukvengers/global/exception/ServiceException.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/service/UserServiceTest.java
  src/test/java/com/prgrms/mukvengers/utils/UserObjectProvider.java
  src/test/resources/schema.sql
Labels: 🚀 Feat, ✅ Test

#18 [#13] 가게 CR 기능 API 구현
  src/main/java/com/prgrms/mukvengers/domain/store/api/StoreController.java
  src/main/java/com/prgrms/mukvengers/domain/store/dto/request/CreateStoreRequest.java
  src/main/java/com/prgrms/mukvengers/domain/store/mapper/StoreMapper.java
  src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java
  src/main/java/com/prgrms/mukvengers/domain/store/repository/StoreRepository.java
  src/main/java/com/prgrms/mukvengers/domain/store/service/DefaultStoreService.java
  src/main/java/com/prgrms/mukvengers/domain/store/service/StoreService.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/model/StoreTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/repository/StoreRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/service/StoreServiceTest.java
  src/test/java/com/prgrms/mukvengers/utils/StoreObjectProvider.java
  src/test/resources/schema.sql
Labels: 🚀 Feat, ✅ Test

#19 [#8, #3] JWT 기반 인증 기능 및 유저 Controller 구현
  build.gradle
  src/main/java/com/prgrms/mukvengers/domain/user/api/UserController.java
  src/main/java/com/prgrms/mukvengers/domain/user/exception/UserNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/user/model/User.java
  src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java
  src/main/java/com/prgrms/mukvengers/global/config/web/WebConfig.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthentication.java
  src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationToken.java
  src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/prgrms/mukvengers/global/security/token/exception/ExceptionHandlerFilter.java
  src/main/java/com/prgrms/mukvengers/global/security/token/exception/ExpiredTokenException.java
  src/main/java/com/prgrms/mukvengers/global/security/token/exception/InvalidTokenException.java
  src/main/java/com/prgrms/mukvengers/global/security/token/exception/TokenException.java
  src/main/java/com/prgrms/mukvengers/global/utils/ExtractUtil.java
  src/main/resources/application-security.yml
  src/main/resources/application-test.yml
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/config/JwtConfig.java
  src/test/java/com/prgrms/mukvengers/domain/user/api/UserControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/model/UserTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationTest.java
  src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProviderTest.java
  src/test/java/com/prgrms/mukvengers/utils/UserObjectProvider.java
  src/test/resources/application.yml
Labels: 🚀 Feat, ✅ Test

#23 [#22] 테스트 DB 환경을 인메모리 기반 H2에서 로컬(외부) MySQL로 변경
  .github/workflows/ci-gradle-build.yml
  src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java
  src/main/resources/application-test.yml
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java
  src/test/resources/application.yml
  src/test/resources/schema.sql
Labels: ♻️ Refactor, ✅ Test, 💣 CI/CD, 🛠 Setting

#21 [#4, #20] Github Action, Docker hub를 이용해 배포
  .github/workflows/ci-gradle-build.yml
  .github/workflows/deploy-to-aws.yml
  Dockerfile
  nginx/conf.d/nginx.conf
Labels: 💣 CI/CD

#30 [#29] prod 서버를 구성한다
  .ebextensions/00-makeFiles.config
  .github/workflows/deploy-to-dev.yml
  .github/workflows/deploy-to-prod.yml
  .platform/nginx/nginx.conf
  Procfile
  nginx/conf.d/nginx.conf
Labels: 💣 CI/CD

#27 [#24] 서버 주소를 변수로 관리
  .github/workflows/deploy-to-dev.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/prgrms/mukvengers/global/config/web/WebConfig.java
Labels: 🛠 Setting

#32 [#28] OAuth를 이용해서 kakao 및 google 로그인 기능 구현
  src/main/java/com/prgrms/mukvengers/domain/user/repository/UserRepository.java
  src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/dto/OAuthUserInfo.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/HttpCookieOAuthAuthorizationRequestRepository.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationFailureHandler.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/mapper/OAuthMapper.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/service/OAuthProvider.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/service/OAuthService.java
  src/main/java/com/prgrms/mukvengers/global/utils/CookieUtil.java
  src/main/resources/application-security.yml
Labels: 🚀 Feat

#31 [#12] 밥 모임 CRU 기능 API 구현
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/CreateCrewRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/UpdateStatusRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewResponses.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewSliceResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/exception/CrewNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/Category.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/Status.java
  src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/store/dto/response/StoreResponse.java
  src/main/java/com/prgrms/mukvengers/domain/store/exception/StoreNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java
  src/main/java/com/prgrms/mukvengers/domain/store/service/StoreServiceImpl.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java
  src/test/java/com/prgrms/mukvengers/base/ServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/store/service/StoreServiceTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
  src/test/java/com/prgrms/mukvengers/utils/StoreObjectProvider.java
Labels: 🚀 Feat, ✅ Test

#33 [#15] Flyway를 이용해 개발 및 테스트 데이터베이스 변경
  src/main/java/com/prgrms/mukvengers/domain/comment/model/Comment.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
  src/main/java/com/prgrms/mukvengers/domain/post/model/Post.java
  src/main/java/com/prgrms/mukvengers/domain/review/model/Review.java
  src/main/resources/db/migration/V2.1__alter_comment_table.sql
  src/main/resources/db/migration/V2.2__alter_crew_table.sql
  src/main/resources/db/migration/V2.3_alter_review_table.sql
  src/main/resources/db/migration/V2__delete_unused_table.sql
  src/test/resources/schema.sql
Labels: ♻️ Refactor, 🛠 Setting

#34 [#24] 기타 오류 해결하기
  .github/workflows/ci-gradle-build.yml
  .github/workflows/deploy-to-dev.yml
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/CreateCrewRequest.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java
  src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
Labels: ♻️ Refactor

#35 [#24] .env에서 설정한 변수명 수정
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: 🐛 Bug

#37 [#36] docker-compose 수정
  docker-compose.yml
Labels: 🐛 Bug, 💣 CI/CD

#43 [#42] 페이지네이션 수정
  src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewPageResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewSliceResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
Labels: ♻️ Refactor, ✅ Test

#48 [#39] prod서버에 SSL 인증서 도입
  .platform/nginx/nginx.conf
Labels: 🛠 Setting
