Repository prgrms-web-devcourse/Team-DarkNight-Kkini-BE, pull requests merged in 2023-05, with the labels that each got.

#204 [#203] 모임원 조회 쿼리 삭제
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
Labels: ♻️ Refactor

#208 Notification 엔티티 생성
  src/main/java/com/prgrms/mukvengers/domain/notification/exception/InvalidNotificationContentException.java
  src/main/java/com/prgrms/mukvengers/domain/notification/model/Notification.java
  src/main/java/com/prgrms/mukvengers/domain/notification/model/vo/NotificationContent.java
  src/main/java/com/prgrms/mukvengers/domain/notification/model/vo/NotificationType.java
  src/main/java/com/prgrms/mukvengers/domain/notification/repository/NotificationRepository.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/main/resources/db/migration/V4.1__alter_notification_table.sql
  src/main/resources/messages/exceptions/exception.properties
  src/test/java/com/prgrms/mukvengers/domain/notification/model/NotificationTest.java
Labels: 🚀 Feat

#209 [#205]테스트 코드 보완 및 Jacoco 적용
  .github/workflows/code-review-by-chat-gpt.yml
  .github/workflows/gradle-build.yml
  build.gradle
  src/main/java/com/prgrms/mukvengers/domain/user/model/User.java
  src/main/java/com/prgrms/mukvengers/global/aws/service/AwsS3Service.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
  src/main/java/com/prgrms/mukvengers/global/security/oauth/service/OAuthProvider.java
  src/main/java/com/prgrms/mukvengers/global/security/token/exception/ExceptionHandlerFilter.java
  src/main/java/com/prgrms/mukvengers/global/security/token/filter/JwtAuthenticationEntryPoint.java
  src/main/java/com/prgrms/mukvengers/global/security/token/service/TokenService.java
  src/main/java/com/prgrms/mukvengers/global/slack/SlackNotificationAspect.java
  src/main/resources/application-test.yml
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/repository/UserRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/global/aws/api/AwsS3ControllerTest.java
  src/test/java/com/prgrms/mukvengers/global/aws/service/AwsS3ServiceTest.java
  src/test/java/com/prgrms/mukvengers/global/config/EmbeddedRedisConfig.java
  src/test/java/com/prgrms/mukvengers/global/config/JwtConfig.java
  src/test/java/com/prgrms/mukvengers/global/config/RestDocsConfig.java
  src/test/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationFailureHandlerTest.java
  src/test/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandlerTest.java
  src/test/java/com/prgrms/mukvengers/global/security/oauth/repository/HttpCookieOAuthAuthorizationRequestRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/global/security/oauth/service/CustomOAuth2UserServiceTest.java
  src/test/java/com/prgrms/mukvengers/global/security/oauth/service/OAuthProviderTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/api/TokenControllerTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/exception/ExceptionHandlerFilterTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/filter/JwtAuthenticationEntryPointTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/filter/JwtAuthenticationFilterTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/model/RefreshTokenTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/repository/TokenRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/service/JwtTokenProviderTest.java
  src/test/java/com/prgrms/mukvengers/global/security/token/service/TokenServiceTest.java
  src/test/java/com/prgrms/mukvengers/global/slack/SlackNotificationAspectTest.java
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: ✅ Test

#213 [#211] SSE를 이용한 알림 기능
  src/main/java/com/prgrms/mukvengers/domain/notification/api/NotificationController.java
  src/main/java/com/prgrms/mukvengers/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/prgrms/mukvengers/domain/notification/dto/response/NotificationResponses.java
  src/main/java/com/prgrms/mukvengers/domain/notification/exception/InvalidNotificationAccessException.java
  src/main/java/com/prgrms/mukvengers/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/notification/mapper/NotificationMapper.java
  src/main/java/com/prgrms/mukvengers/domain/notification/model/Notification.java
  src/main/java/com/prgrms/mukvengers/domain/notification/repository/EmitterRepository.java
  src/main/java/com/prgrms/mukvengers/domain/notification/repository/MemoryEmitterRepository.java
  src/main/java/com/prgrms/mukvengers/domain/notification/repository/NotificationRepository.java
  src/main/java/com/prgrms/mukvengers/domain/notification/service/NotificationService.java
  src/main/java/com/prgrms/mukvengers/domain/notification/util/NotificationFactory.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/main/resources/db/migration/V4.2__alter_notification_table.sql
  src/main/resources/messages/exceptions/exception.properties
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/api/NotificationControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/model/NotificationTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/repository/EmitterRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/util/NotificationFactoryTest.java
  src/test/java/com/prgrms/mukvengers/utils/NotificationObjectProvider.java
  src/test/resources/schema.sql
Labels: 🚀 Feat

#215 [#206] 알림 기능을 구현한다
  src/main/java/com/prgrms/mukvengers/domain/notification/api/NotificationController.java
  src/main/java/com/prgrms/mukvengers/domain/notification/dto/response/NotificationResponse.java
  src/main/java/com/prgrms/mukvengers/domain/notification/dto/response/NotificationResponses.java
  src/main/java/com/prgrms/mukvengers/domain/notification/exception/InvalidNotificationAccessException.java
  src/main/java/com/prgrms/mukvengers/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/com/prgrms/mukvengers/domain/notification/mapper/NotificationMapper.java
  src/main/java/com/prgrms/mukvengers/domain/notification/model/Notification.java
  src/main/java/com/prgrms/mukvengers/domain/notification/repository/EmitterRepository.java
  src/main/java/com/prgrms/mukvengers/domain/notification/repository/MemoryEmitterRepository.java
  src/main/java/com/prgrms/mukvengers/domain/notification/repository/NotificationRepository.java
  src/main/java/com/prgrms/mukvengers/domain/notification/service/NotificationService.java
  src/main/java/com/prgrms/mukvengers/domain/notification/util/NotificationFactory.java
  src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java
  src/main/resources/db/migration/V4.2__alter_notification_table.sql
  src/main/resources/messages/exceptions/exception.properties
  src/test/java/com/prgrms/mukvengers/base/ControllerTest.java
  src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/api/NotificationControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/model/NotificationTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/repository/EmitterRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/repository/NotificationRepositoryTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/service/NotificationServiceTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/util/NotificationFactoryTest.java
  src/test/java/com/prgrms/mukvengers/utils/NotificationObjectProvider.java
  src/test/resources/schema.sql
Labels: 🚀 Feat

#219 refactor(proposal): 신청서 조회 페이지네이션 적용
  src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/dto/response/ProposalPageResponse.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
Labels: ♻️ Refactor

#223 [#221] Store내 병목 현상을 유발하는 코드 제거
  src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java
Labels: ♻️ Refactor

#224 [#218] 알림 발송 기능
  src/main/java/com/prgrms/mukvengers/domain/notification/aop/PushNotificationAspect.java
  src/main/java/com/prgrms/mukvengers/domain/notification/aop/annotation/PushNotification.java
  src/main/java/com/prgrms/mukvengers/domain/notification/model/vo/MessageKey.java
  src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/messages/notification/messages.properties
  src/test/java/com/prgrms/mukvengers/domain/notification/aop/PushNotificationAspectTest.java
  src/test/java/com/prgrms/mukvengers/domain/notification/model/vo/MessageKeyTest.java
Labels: 🚀 Feat

#226 [#225] 내 밥모임 조회 응답 필드 변경
  src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/MyCrewResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java
  src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/dto/response/MyCrewMemberResponse.java
  src/main/java/com/prgrms/mukvengers/domain/crewmember/mapper/CrewMemberMapper.java
  src/main/java/com/prgrms/mukvengers/domain/user/repository/UserRepository.java
  src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
Labels: ♻️ Refactor

#227 [#222] 유저 도메인에 캐시 적용
  build.gradle
  src/main/java/com/prgrms/mukvengers/domain/user/service/DefaultUserService.java
  src/main/java/com/prgrms/mukvengers/global/config/cache/CacheConfig.java
  src/main/java/com/prgrms/mukvengers/global/config/redis/RedisConfig.java
  src/test/java/com/prgrms/mukvengers/domain/user/api/UserControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/user/service/UserServiceTest.java
Labels: 🚀 Feat

#220 [#205] 채팅 테스트
  src/test/java/com/prgrms/mukvengers/domain/chat/api/ChatControllerTest.java
  src/test/java/com/prgrms/mukvengers/domain/chat/handler/StompHandlerTest.java
  src/test/java/com/prgrms/mukvengers/domain/chat/handler/WebSocketEventListenerTest.java
  src/test/java/com/prgrms/mukvengers/utils/ChatObjectProvider.java
Labels: ✅ Test
